if(NOT WIN32)
  string(ASCII 27 ESC)
  set(RESET "${ESC}[m")
  set(BOLD "${ESC}[1m")
  set(RED "${ESC}[31m")
  set(GREEN "${ESC}[32m")
  set(YELLOW "${ESC}[33m")
  set(BLUE "${ESC}[34m")
  set(MAGENTA "${ESC}[35m")
  set(CYAN "${ESC}[36m")
  set(WHITE "${ESC}[37m")
  set(BOLD_RED "${ESC}[1;31m")
  set(BOLD_GREEN "${ESC}[1;32m")
  set(BOLD_YELLOW "${ESC}[1;33m")
  set(BOLD_BLUE "${ESC}[1;34m")
  set(BOLD_MAGENTA "${ESC}[1;35m")
  set(BOLD_CYAN "${ESC}[1;36m")
  set(BOLD_WHITE "${ESC}[1;37m")
endif()
